sharding:
  jdbc:
    datasource:
      names: ds0
      # 数据源ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sharding_test_01?characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
        username: root
        password: q1w2e3r4
    config:
      sharding:
        props:
          sql.show: true
        tables:
          t_user:  #t_user表
            key-generator-column-name: id  #主键
            actual-data-nodes: ds0.t_user${0..1}    #数据节点,均匀分布
            table-strategy:  #分表策略
              standard:
                sharding-column: sex
                #精确分片算法类名称，用于=和IN。该类需实现PreciseShardingAlgorithm接口并提供无参数的构造器
                precise-algorithm-class-name: com.yapt.demo.user.core.common.sharding.ShardingStrategy
                #范围分片算法类名称，用于BETWEEN，可选。该类需实现RangeShardingAlgorithm接口并提供无参数的构造器
                #range-algorithm-class-name:
      #行表达式 inline:
      #行表达式 sharding-column: sex
      #行表达式 algorithm-expression: t_user${sex % 2}#按模运算分配



