sharding:
  jdbc:
    datasource:
      # 注意：数据库名称的命名一定不能使用下划线！！！
      names: ds0,ds0-slave0,ds0-slave1,ds1,ds1-slave0,ds1-slave1
      # 主库0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds0?characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
        username: root
        password: q1w2e3r4
      # 主库0的从库0
      ds0-slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/ds0?characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
        username: root
        password: q1w2e3r4

      # 主库0的从库1
      ds0-slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3308/ds0?characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
        username: root
        password: q1w2e3r4

      # 主库1
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds1?characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
        username: root
        password: q1w2e3r4
      # 主库1的从库0
      ds1-slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/ds1?characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
        username: root
        password: q1w2e3r4

      # 主库1的从库1
      ds1-slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3308/ds1?characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
        username: root
        password: q1w2e3r4


    # 配置读写分离
    config:
      sharding:
        props:
          sql.show: true
        #配置分库分表
        tables:
          t_user:
            key-generator-column-name: id  #主键
            actual-data-nodes: ds${0..1}.t_user${0..1}    #数据节点,均匀分布
            database-strategy:   #分库策略
              inline: #行表达式
                sharding-column: city_id        #列名称，多个列以逗号分隔
                algorithm-expression: ds${city_id % 2}    #按模运算分配
            table-strategy:  #分表策略
              inline: #行表达式
                sharding-column: sex
                algorithm-expression: t_user${sex % 2}
        #配置读写分离
        master-slave-rules:
          ds0:
            master-data-source-name: ds0
            slave-data-source-names: ds0-slave0,ds0-slave1
            load-balance-algorithm-type: random
          ds1:
            master-data-source-name: ds1
            slave-data-source-names: ds1-slave0,ds1-slave1
            load-balance-algorithm-type: random





